import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Counter from '../src/feature/counter/Counter'
import User from '../src/components/Users'
import { useEffect } from 'react'
import useAxios from '../src/helpers/useAxios'
import {fetchData} from '../src/feature/user/userSlice'
import { useDispatch } from 'react-redux'
import AddDrawer from '../src/views/AddDrawer'
import UpdateDrawer from '../src/views/UpdateDrawer'
import NewForm from '../src/views/NewForm'
import DataGrid from '../src/components/DataGridTable'

const Home: NextPage = () => {
  console.log(process.env.NEXT_PUBLIC_BASE_URL_USER)
  const dispatch = useDispatch();
 useEffect( ()=>{

    // dispatch(fetchData())
  
    // useAxios.GET(`${process.env.NEXT_PUBLIC_BASE_URL_USER}/users`).then(res=>console.log(res))

 },[]) 
  return (
    
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/* <Test name={"manihs"} onClick ={(e)=>{console.log(e.target.id)}} /> */}
    {/* <Counter/> */}
    {/* <User/> */}
    <AddDrawer/>
    <UpdateDrawer/>
    <NewForm/>
    <DataGrid/>
      
    </>
  )
}


const Test = (props)=>{
  return (
    <>
     <button id="lll" {...props} >click herer {props.name} </button>
    </>
  )
}

export default Home
